SCREEN_WIDTH = 2440
SCREEN_HEIGHT = 1280
WINDOW_SCALE = 1

# Window size:
WINDOW_WIDTH = SCREEN_WIDTH * WINDOW_SCALE
WINDOW_HEIGHT = SCREEN_HEIGHT * WINDOW_SCALE
# Camera zoom
ZOOM = 1
# Center position
SCREEN_CENTER_POS = (SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2)
# Game Volume
VOLUME = 0.7

TITLE = "RPG"
# Scale of all images
SCALE = 2

# Tile size
TILE_SIZE = 64
