SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 800
WINDOW_SCALE = 1
# Window size:
WINDOW_WIDTH = SCREEN_WIDTH * WINDOW_SCALE
WINDOW_HEIGHT = SCREEN_HEIGHT * WINDOW_SCALE
# Camera zoom
ZOOM = 2
# Center position
SCREEN_CENTER_POS = (SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2)
# Game Volume
VOLUME = 0.7

TITLE = "RPG"
# Scale of all images
SCALE = 2
# Tile size
TILE_SIZE = 32 * SCALE
SUB_TILE_RESOLUTION = 4
SUB_TILE_SIZE = 32
